In [1]:
import pandas as pd
import numpy as np

## **Load Data and Data Preprocessing**

In [15]:
df1 = pd.read_csv("C:\\Users\\ayank\\OneDrive\\Desktop\\mini project\\Data Collection\\merged_1star.txt")
df1

,SrNo,Timestamp,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Rating
0,1,1.739350e+12,-0.79173,-4.23709,9.16870,-4.71483,6.08045,12.31348,1
1,2,1.739350e+12,-0.44716,2.18525,10.64028,-21.07940,5.18784,4.70720,1
2,3,1.739350e+12,-1.50957,-2.00219,8.74278,17.42121,1.83863,12.03883,1
3,4,1.739350e+12,-0.76301,-0.42532,9.33620,1.31222,1.78523,5.42052,1
4,5,1.739350e+12,-0.18395,-1.60259,9.29313,-21.75076,0.30898,-4.25326,1
...,...,...,...,...,...,...,...,...,...
574895,574896,1.771570e+12,-1.53795,6.70905,6.05700,-3.04885,32.85197,-4.84507,1
574896,574897,1.771570e+12,-1.77705,6.73305,6.75105,-5.60926,24.80836,-4.72690,1
574897,574898,1.771570e+12,-1.60200,6.72105,6.91905,-8.95748,13.70802,-4.12028,1
574898,574899,1.771570e+12,-1.12800,6.73005,7.27095,-9.44593,8.16178,-5.21535,1
574899,574900,1.771570e+12,-1.12800,6.73005,7.27095,-8.47691,6.45222,-7.28731,1

In [16]:
df2 = pd.read_csv("C:\\Users\\ayank\\OneDrive\\Desktop\\mini project\\Data Collection\\merged_2star.txt")
df2

,SrNo,Timestamp,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Rating
0,1,1.739350e+12,-0.96790,-1.29452,9.83719,-7.15616,7.56814,8.25476,2
1,2,1.739350e+12,-1.18834,-1.64686,10.35464,4.62328,-4.76060,8.37683,2
2,3,1.739350e+12,-0.49831,-1.96540,9.07538,-0.80869,10.13154,8.55993,2
3,4,1.739350e+12,-0.49831,-1.96540,9.07538,2.18194,-5.85920,9.41440,2
4,5,1.739350e+12,-1.25055,-1.28495,9.81326,4.74534,4.45543,7.27823,2
...,...,...,...,...,...,...,...,...,...
486176,486177,1.771430e+12,-2.22182,4.28083,5.94480,-1.33000,7.91000,9.52000,2
486177,486178,1.771430e+12,-1.30723,4.76446,7.20894,-18.30500,-16.24000,8.26000,2
486178,486179,1.771430e+12,0.13647,4.30956,10.30464,-6.40500,-13.12500,-4.97000,2
486179,486180,1.771430e+12,-1.00078,4.17549,9.71328,12.56500,-4.13000,-9.87000,2
486180,486181,1.771430e+12,-1.37188,3.81157,7.68539,14.38500,-7.14000,-6.72000,2

In [17]:
df3 = pd.read_csv("C:\\Users\\ayank\\OneDrive\\Desktop\\mini project\\Data Collection\\merged_3star.txt")
df3

,SrNo,Timestamp,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Rating
0,1,1.739350e+12,0.05414,-1.63878,10.04896,1.17108,1.43810,-5.77528,3
1,2,1.739350e+12,2.16461,-1.21047,10.21406,1.21304,1.88440,-5.64940,3
2,3,1.739350e+12,1.35823,-0.74626,9.37657,0.66374,2.05988,-5.88209,3
3,4,1.739350e+12,1.35823,-0.74626,9.37657,-0.90406,3.27673,-6.56872,3
4,5,1.739350e+12,0.56142,-2.25853,9.11815,-4.73771,5.17258,-8.44168,3
...,...,...,...,...,...,...,...,...,...
705877,705878,1.771510e+12,-6.48300,3.86505,6.58800,13.00686,-4.08089,-5.38079,3
705878,705879,1.771510e+12,-8.35005,3.37395,5.97705,12.27419,-5.42018,-0.99265,3
705879,705880,1.771510e+12,-8.35005,3.37395,5.97705,14.16495,-12.13238,-2.08771,3
705880,705881,1.771510e+12,-6.90195,3.79995,5.83095,11.05307,-10.60402,-1.96166,3
705881,705882,1.771510e+12,-6.37995,3.88395,5.17500,4.04150,-8.40601,-4.04150,3

In [18]:
df4 = pd.read_csv("C:\\Users\\ayank\\OneDrive\\Desktop\\mini project\\Data Collection\\merged_4star.txt")

In [19]:
df4 = df4.dropna(axis=1, how='all')
df4

,SrNo,Timestamp,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Rating
0,1.0,1.739350e+12,-0.11400,-2.89605,9.76905,-1.91440,0.81933,6.58615,4.0
1,2.0,1.739350e+12,0.30705,-2.58000,9.73305,1.93803,2.14286,6.72796,4.0
2,3.0,1.739350e+12,0.30705,-2.58000,9.73305,6.27890,1.23687,7.70485,4.0
3,4.0,1.739350e+12,1.69500,-1.75905,10.26705,7.11399,-1.55988,5.53835,4.0
4,5.0,1.739350e+12,1.69500,-1.75905,10.26705,6.83825,1.23687,5.74319,4.0
...,...,...,...,...,...,...,...,...,...
812489,20338.0,1.771430e+12,-0.56595,-0.39405,10.54605,2.99370,-1.70168,-6.16073,NaN
812490,20339.0,1.771430e+12,-0.56595,-0.39405,10.54605,2.14286,-1.40231,-6.52312,NaN
812491,20340.0,1.771430e+12,0.57795,-0.65205,9.27405,0.43330,-0.96901,-6.34193,NaN
812492,20341.0,1.771430e+12,0.57795,-0.65205,9.27405,-0.17332,-0.60662,-6.52312,NaN
812493,20342.0,1.771430e+12,1.13505,-0.78600,8.67795,0.18908,-2.43435,-6.27890,NaN

In [20]:
df5 = pd.read_csv("C:\\Users\\ayank\\OneDrive\\Desktop\\mini project\\Data Collection\\merged_5star.txt")
df5

,Sr.No.,Timestamp,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Rating
0,1,1.771330e+12,-2.40795,0.27600,10.99095,-14.82672,-0.81933,14.87398,5
1,2,1.771330e+12,-3.29700,0.52905,9.94305,-11.65181,-18.45855,24.09144,5
2,3,1.771330e+12,-3.29700,0.52905,9.94305,-10.91914,-29.13347,30.86667,5
3,4,1.771330e+12,-1.70400,0.63495,8.88405,-13.18018,-33.71069,33.12770,5
4,5,1.771330e+12,-0.05700,0.73005,9.45195,-15.62241,-33.10407,25.61981,5
...,...,...,...,...,...,...,...,...,...
430092,430093,1.771240e+12,2.41336,7.68539,-5.58807,-0.98000,7.77000,-1.71500,5
430093,430094,1.771240e+12,2.16196,8.05649,-5.43244,-1.82000,2.10000,0.21000,5
430094,430095,1.771240e+12,2.66714,8.07085,-4.76446,0.70000,-4.02500,1.01500,5
430095,430096,1.771240e+12,2.66714,8.07085,-4.76446,2.52000,-6.16000,0.94500,5
430096,430097,1.771240e+12,2.73657,8.05409,-5.37498,-1.40000,-2.62500,0.00000,5

In [21]:
df5.rename(columns={'Sr.No.': 'SrNo'}, inplace=True)
df5

,SrNo,Timestamp,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Rating
0,1,1.771330e+12,-2.40795,0.27600,10.99095,-14.82672,-0.81933,14.87398,5
1,2,1.771330e+12,-3.29700,0.52905,9.94305,-11.65181,-18.45855,24.09144,5
2,3,1.771330e+12,-3.29700,0.52905,9.94305,-10.91914,-29.13347,30.86667,5
3,4,1.771330e+12,-1.70400,0.63495,8.88405,-13.18018,-33.71069,33.12770,5
4,5,1.771330e+12,-0.05700,0.73005,9.45195,-15.62241,-33.10407,25.61981,5
...,...,...,...,...,...,...,...,...,...
430092,430093,1.771240e+12,2.41336,7.68539,-5.58807,-0.98000,7.77000,-1.71500,5
430093,430094,1.771240e+12,2.16196,8.05649,-5.43244,-1.82000,2.10000,0.21000,5
430094,430095,1.771240e+12,2.66714,8.07085,-4.76446,0.70000,-4.02500,1.01500,5
430095,430096,1.771240e+12,2.66714,8.07085,-4.76446,2.52000,-6.16000,0.94500,5
430096,430097,1.771240e+12,2.73657,8.05409,-5.37498,-1.40000,-2.62500,0.00000,5

In [22]:
files = [
    df1,
    df2,
    df3,
    df4,
    df5
]

# Read all files into separate dataframes
dfs = []

for file in files:
    dfs.append(file)

In [23]:
# Merge all dataframes
merged_df = pd.concat(dfs, ignore_index=True)

# Show dataset shape
print("Merged Dataset Shape:", merged_df.shape)

Merged Dataset Shape: (3009554, 9)

In [24]:
merged_df

,SrNo,Timestamp,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Rating
0,1.0,1.739350e+12,-0.79173,-4.23709,9.16870,-4.71483,6.08045,12.31348,1.0
1,2.0,1.739350e+12,-0.44716,2.18525,10.64028,-21.07940,5.18784,4.70720,1.0
2,3.0,1.739350e+12,-1.50957,-2.00219,8.74278,17.42121,1.83863,12.03883,1.0
3,4.0,1.739350e+12,-0.76301,-0.42532,9.33620,1.31222,1.78523,5.42052,1.0
4,5.0,1.739350e+12,-0.18395,-1.60259,9.29313,-21.75076,0.30898,-4.25326,1.0
...,...,...,...,...,...,...,...,...,...
3009549,430093.0,1.771240e+12,2.41336,7.68539,-5.58807,-0.98000,7.77000,-1.71500,5.0
3009550,430094.0,1.771240e+12,2.16196,8.05649,-5.43244,-1.82000,2.10000,0.21000,5.0
3009551,430095.0,1.771240e+12,2.66714,8.07085,-4.76446,0.70000,-4.02500,1.01500,5.0
3009552,430096.0,1.771240e+12,2.66714,8.07085,-4.76446,2.52000,-6.16000,0.94500,5.0
3009553,430097.0,1.771240e+12,2.73657,8.05409,-5.37498,-1.40000,-2.62500,0.00000,5.0

In [26]:
# Preview dataset
print(merged_df.head())

   SrNo     Timestamp    X_Acc    Y_Acc     Z_Acc    X_Gyro   Y_Gyro  \
0   1.0  1.739350e+12 -0.79173 -4.23709   9.16870  -4.71483  6.08045
1   2.0  1.739350e+12 -0.44716  2.18525  10.64028 -21.07940  5.18784
2   3.0  1.739350e+12 -1.50957 -2.00219   8.74278  17.42121  1.83863
3   4.0  1.739350e+12 -0.76301 -0.42532   9.33620   1.31222  1.78523
4   5.0  1.739350e+12 -0.18395 -1.60259   9.29313 -21.75076  0.30898

     Z_Gyro  Rating
0  12.31348     1.0
1   4.70720     1.0
2  12.03883     1.0
3   5.42052     1.0
4  -4.25326     1.0

In [27]:
df = merged_df.copy()

In [28]:
df

,SrNo,Timestamp,X_Acc,Y_Acc,Z_Acc,X_Gyro,Y_Gyro,Z_Gyro,Rating
0,1.0,1.739350e+12,-0.79173,-4.23709,9.16870,-4.71483,6.08045,12.31348,1.0
1,2.0,1.739350e+12,-0.44716,2.18525,10.64028,-21.07940,5.18784,4.70720,1.0
2,3.0,1.739350e+12,-1.50957,-2.00219,8.74278,17.42121,1.83863,12.03883,1.0
3,4.0,1.739350e+12,-0.76301,-0.42532,9.33620,1.31222,1.78523,5.42052,1.0
4,5.0,1.739350e+12,-0.18395,-1.60259,9.29313,-21.75076,0.30898,-4.25326,1.0
...,...,...,...,...,...,...,...,...,...
3009549,430093.0,1.771240e+12,2.41336,7.68539,-5.58807,-0.98000,7.77000,-1.71500,5.0
3009550,430094.0,1.771240e+12,2.16196,8.05649,-5.43244,-1.82000,2.10000,0.21000,5.0
3009551,430095.0,1.771240e+12,2.66714,8.07085,-4.76446,0.70000,-4.02500,1.01500,5.0
3009552,430096.0,1.771240e+12,2.66714,8.07085,-4.76446,2.52000,-6.16000,0.94500,5.0
3009553,430097.0,1.771240e+12,2.73657,8.05409,-5.37498,-1.40000,-2.62500,0.00000,5.0

In [29]:
df = df.drop(columns=["SrNo"], errors="ignore")
df.columns = df.columns.str.strip().str.lower()

In [30]:
df

,timestamp,x_acc,y_acc,z_acc,x_gyro,y_gyro,z_gyro,rating
0,1.739350e+12,-0.79173,-4.23709,9.16870,-4.71483,6.08045,12.31348,1.0
1,1.739350e+12,-0.44716,2.18525,10.64028,-21.07940,5.18784,4.70720,1.0
2,1.739350e+12,-1.50957,-2.00219,8.74278,17.42121,1.83863,12.03883,1.0
3,1.739350e+12,-0.76301,-0.42532,9.33620,1.31222,1.78523,5.42052,1.0
4,1.739350e+12,-0.18395,-1.60259,9.29313,-21.75076,0.30898,-4.25326,1.0
...,...,...,...,...,...,...,...,...
3009549,1.771240e+12,2.41336,7.68539,-5.58807,-0.98000,7.77000,-1.71500,5.0
3009550,1.771240e+12,2.16196,8.05649,-5.43244,-1.82000,2.10000,0.21000,5.0
3009551,1.771240e+12,2.66714,8.07085,-4.76446,0.70000,-4.02500,1.01500,5.0
3009552,1.771240e+12,2.66714,8.07085,-4.76446,2.52000,-6.16000,0.94500,5.0
3009553,1.771240e+12,2.73657,8.05409,-5.37498,-1.40000,-2.62500,0.00000,5.0

In [31]:
# Convert timestamp
df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")

In [32]:
# Remove missing values
df = df.dropna()

In [33]:
df

,timestamp,x_acc,y_acc,z_acc,x_gyro,y_gyro,z_gyro,rating
0,2025-02-12 08:46:40,-0.79173,-4.23709,9.16870,-4.71483,6.08045,12.31348,1.0
1,2025-02-12 08:46:40,-0.44716,2.18525,10.64028,-21.07940,5.18784,4.70720,1.0
2,2025-02-12 08:46:40,-1.50957,-2.00219,8.74278,17.42121,1.83863,12.03883,1.0
3,2025-02-12 08:46:40,-0.76301,-0.42532,9.33620,1.31222,1.78523,5.42052,1.0
4,2025-02-12 08:46:40,-0.18395,-1.60259,9.29313,-21.75076,0.30898,-4.25326,1.0
...,...,...,...,...,...,...,...,...
3009549,2026-02-16 11:06:40,2.41336,7.68539,-5.58807,-0.98000,7.77000,-1.71500,5.0
3009550,2026-02-16 11:06:40,2.16196,8.05649,-5.43244,-1.82000,2.10000,0.21000,5.0
3009551,2026-02-16 11:06:40,2.66714,8.07085,-4.76446,0.70000,-4.02500,1.01500,5.0
3009552,2026-02-16 11:06:40,2.66714,8.07085,-4.76446,2.52000,-6.16000,0.94500,5.0
3009553,2026-02-16 11:06:40,2.73657,8.05409,-5.37498,-1.40000,-2.62500,0.00000,5.0

In [34]:
df = df.drop(columns=["timestamp"], errors="ignore")

In [37]:
df = df.reset_index(drop=True)

In [38]:
# final dataset
df.to_csv("final_driving_dataset.csv", index=False)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

XGBoost

In [ ]:
!pip install xgboost --upgrade

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.27.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

xgb = XGBClassifier(
    n_estimators=150,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method='hist',
    device='cuda',
    random_state=42
)

# Adjust y_train and y_test to be 0-indexed for XGBoost
y_train_adjusted = y_train - 1
y_test_adjusted = y_test - 1

xgb.fit(X_train_scaled, y_train_adjusted)

xgb_pred = xgb.predict(X_test_scaled)

print("XGBoost Accuracy:", accuracy_score(y_test_adjusted, xgb_pred))
print(classification_report(y_test_adjusted, xgb_pred))

/usr/local/lib/python3.12/dist-packages/xgboost/core.py:751: UserWarning: [17:55:59] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

XGBoost Accuracy: 0.5552921044117898
              precision    recall  f1-score   support

         0.0       0.54      0.53      0.53    114980
         1.0       0.60      0.44      0.51     97236
         2.0       0.50      0.70      0.58    141177
         3.0       0.62      0.23      0.33     30420
         4.0       0.68      0.60      0.63     86019

    accuracy                           0.56    469832
   macro avg       0.59      0.50      0.52    469832
weighted avg       0.57      0.56      0.55    469832

In [ ]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

xgb_params = {
    "n_estimators": [200,300],
    "max_depth": [4,6,8],
    "learning_rate": [0.01,0.05,0.1]
}

xgb_grid = GridSearchCV(
    XGBClassifier(), # Explicitly setting device to cpu
    xgb_params,
    cv=3,
    n_jobs=-1,
    verbose=1
)

# Adjust y_train to be 0-indexed for GridSearchCV
xgb_grid.fit(X_train_scaled, y_train_adjusted)

best_xgb = xgb_grid.best_estimator_

Fitting 3 folds for each of 18 candidates, totalling 54 fits

In [ ]:
# Make predictions with the best estimator
best_xgb_pred = best_xgb.predict(X_test_scaled)

# Evaluate the best estimator
print("Optimized XGBoost Accuracy:", accuracy_score(y_test_adjusted, best_xgb_pred))
print(classification_report(y_test_adjusted, best_xgb_pred))

Optimized XGBoost Accuracy: 0.5693247799213336
              precision    recall  f1-score   support

         0.0       0.54      0.56      0.55    114980
         1.0       0.62      0.46      0.53     97236
         2.0       0.51      0.70      0.59    141177
         3.0       0.62      0.26      0.36     30420
         4.0       0.69      0.61      0.65     86019

    accuracy                           0.57    469832
   macro avg       0.60      0.52      0.54    469832
weighted avg       0.58      0.57      0.56    469832